### ISSUE TITLE
[APO-1] Manga support 

### ISSUE THREAD

**Issue by HalfBloodprinc3** [ApolloTv-team/ApolloTv#10]
<p>Could you please implement the manga section in your app. Actually I love to read mangas ,but it is hepatic to access those from the web.</p>
<p>And if you are planning to do so,then add an inbuilt reading mode feature and brightness control function so the users can read for a long time without any difficulty. And maybe you can add scroll reading and slide reading for efficient use.</p>
<p>And at last, include a function so that users can continue their reading from where they left. </p>

**Comment by TDanks2000** [comment]
Manga support and a manga reader will be added on the next release along with some other fixes and improvements

**Comment by HalfBloodprinc3** [comment]
> Manga support and a manga reader will be added on the next release along with some other fixes and improvements

Okay...thank you 😊

**Comment by TDanks2000** [comment]
release v0.0.7 now has manga support, thank you for using my app <3
