### ISSUE TITLE
Nav Button Gone

### ISSUE THREAD

**Issue by MrConqueror** [ApolloTv-team/ApolloTv#13]
![Screenshot_2023-08-06-08-15-52-166_com apollotv-edit](https://github.com/ApolloTv-team/ApolloTv/assets/102837820/b127edba-89a2-4aeb-a196-21d7cb3d6756)
Compared to prev version, the new update doesn't show these two things

**Comment by TDanks2000** [comment]
That's international, just swipe up from the bottom to get the system nav back
