### ISSUE TITLE
Android/Google TV Support

### ISSUE THREAD

**Issue by Makar8000** [ApolloTv-team/ApolloTv#20]
There are not many apps out there that work well with Android/Google TV. Most of the popular ones are unmaintained forks or stopped working due to a lack of updates.

Since this seems to be early in development, I figured it would be nice to try to keep in mind support for TVs.

**Comment by TDanks2000** [comment]
I have looked into this before but react native doesnt seem to play nicely with tv's

in the future there will be a cast option to be able to cast to the app on other devices.

if anyone wanted to try to get this app to work on android/google tv then that would be amazing

**Comment by Makar8000** [comment]
After trying this out on TV the primary problem is that there is no way of knowing which Pressable is currently focused. I have tried adding `onFocus` events to set a border once a Pressable is focused, but they don't seem to fire or work at all.

I did some searching and I think using the react-native fork `react-native-tvos` would help resolve this, but I'm not really sure how interested you would be in switching to that just for TV support.

**Comment by TDanks2000** [comment]
ive used react-native-tvos i could try using it but idk if it would break the mobile version of the app

**Comment by TDanks2000** [comment]
if you wanna give it a go https://github.com/react-native-tvos/react-native-template-typescript-tv/tree/main/template

**Comment by Makar8000** [comment]
The repo advertises itself as a full fork of the original repo with only the changes required to give better TV support. I may give it a try when I have some time with this repo and see how it goes.

**Comment by Makar8000** [comment]
Closing this since TV support is at a point where it works fairly well - others can open a new one for more specific issues
