### ISSUE TITLE
Seek bar timing

### ISSUE THREAD

**Issue by Shebyyy** [ApolloTv-team/ApolloTv#22]
Video Player Seek bar starting at 30:00 mins
Please check and fix this issue

![Screenshot_20230918_001021.jpg](https://github.com/ApolloTv-team/ApolloTv/assets/83452219/f9a51a4f-7138-443d-a655-5112bac597fa)

**Comment by TDanks2000** [comment]
I've never experienced this issue could you go into more detail does it happen on every anime certain animes how did you get this error

**Comment by Shebyyy** [comment]
Yes, it happens in every anime
At first i thought it was only in one anime
But after I checked other anime the same thing happened.

I'm not sure, i tried the previous version same bug
Tried uninstall & install
Clear cache & clear data

**Comment by TDanks2000** [comment]
> Yes, it happens in every anime At first i thought it was only in one anime But after I checked other anime the same thing happened.
> 
> I'm not sure, i tried the previous version same bug Tried uninstall & install Clear cache & clear data

that is very confusing i am not getting that bug

![image](https://github.com/ApolloTv-team/ApolloTv/assets/40835340/a3fb71a7-4146-47cf-9905-753a72ab95f9)

**Comment by Shebyyy** [comment]
Maybe it happening in my device only 😅

**Comment by TDanks2000** [comment]
> Maybe it's happening in my device only 😅

what device and android version are you using?

**Comment by TDanks2000** [comment]
im going to do a new build and put it here, could you please clear cache and data of the current version and install the one i will send?

**Comment by TDanks2000** [comment]
[android-test.apk](https://drive.google.com/file/d/1P8QDQ2EIK71lB_EQ7AAH7xNelmQ1VG_T/view?usp=sharing)

**Comment by Shebyyy** [comment]
> [android-test.apk](https://drive.google.com/file/d/1P8QDQ2EIK71lB_EQ7AAH7xNelmQ1VG_T/view?usp=sharing)

Fixed thanks

**Comment by TDanks2000** [comment]
> > [android-test.apk](https://drive.google.com/file/d/1P8QDQ2EIK71lB_EQ7AAH7xNelmQ1VG_T/view?usp=sharing)
> 
> Fix bug, thanks And also got News options.

hehe sneak peak of the next updates 

thank you for using my app :)
