### ISSUE TITLE
Navigation button 

### ISSUE THREAD

**Issue by MrConqueror** [ApolloTv-team/ApolloTv#8]
when i watch my navigation still show it bothers me 

![Screenshot_2023-07-18-20-19-59-974_com apollotv](https://github.com/ApolloTv-team/ApolloTv/assets/102837820/9702f168-f89a-40e0-9f6c-98d27d8f5e06)

it should be like this
![Screenshot_2023-07-18-20-20-39-963_app nekko to](https://github.com/ApolloTv-team/ApolloTv/assets/102837820/17db99a4-d938-409a-9501-a0d4369a5027)

**Comment by TDanks2000** [comment]
fixed in the next release
