### ISSUE TITLE
Blank Lists and not working Video Player setting 

### ISSUE THREAD

**Issue by HalfBloodprinc3** [ApolloTv-team/ApolloTv#9]
The list tab is blank and when I click the back button of my phone it closes the app, . And I have to restart the app to get the home page.

Also when I click the video player settings, nothing happens.

https://github.com/ApolloTv-team/ApolloTv/assets/122849491/79a1c4e8-d274-4345-964a-2186aa883f50

**Comment by TDanks2000** [comment]
"Also when I click the video player settings, nothing happens." 

thats cause thats not implemented yet
